### ISSUE TITLE
Broken mobile responsiveness

### ISSUE THREAD

**Issue by ramacabrera** [TailGrids/play-tailwind#1]
There is an image generating an overflow on x axis when navigating on mobile browsers.

Image Element Xpath -> //*[@id="home"]/div/div/div[2]/div/div[3]
Image Div Container -> <div class="absolute z-[-1] -top-6 -right-6">

Changing -right-6 to -right-2 solved the problem.

![Mobile Home Screenshot](https://user-images.githubusercontent.com/15189062/162779869-461d9453-f515-4ec4-bb6a-d22faa0f58fa.png)

**Comment by Musharofchy** [comment]
Thanks for reporting, resolved!
