### ISSUE TITLE
CSS Not Working Well

### ISSUE THREAD

**Issue by drethedevjs** [TailGrids/play-tailwind#2]
**Browser**: Chrome
**OS**: macOS v.13.2
**Processor**: M1 Chip
**CRA**: v.6.2.0

I doubt this is an issue with your code and more of an issue with my code. So here's the thing...
I have a react app (CRA, craco v.6) that I've been working on and I was looking for a theme to make it look better. So I started with the home page. I downloaded your repo and slowly moved necessary files to my app.

Now, I believe I have everything set but not all the styling is being used.

<img width="1450" alt="CleanShot 2023-03-07 at 12 36 11@2x" src="https://user-images.githubusercontent.com/40521589/223503268-723b8a5b-2288-47aa-a90d-4f9c598b6d6a.png">

I'm using tailwind `npm:@tailwindcss/postcss7-compat@^2.2.17` and tailgrids v.2.0.1. Do I need to use the latest version of tailwind?

**Comment by Musharofchy** [comment]
This template is independent from TailGrids, did you run build command before trying to use it?
